import React from "react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

const Project = () => {
  return (
    <div>
      <h1 className=" text-dark_heading">
        <Link href="/">Home</Link>
      </h1>
    </div>
  );
};

export default Project;
