import React from "react";
import { Metadata } from "next";
import ProjectShowCase from "../components/Contents/ProjectShowCase";
import { GetProjectData } from "../_lib/SanityFetch";

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

const Project = async () => {
  const projectData: any = (await GetProjectData()) || [];

  return (
    <>
      <ProjectShowCase trimProjectCard={false} projectData={projectData} />
    </>
  );
};

export default Project;
