import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-dark_primary_background `}>
        <div className="flex">
          <NavBar />
          <div className=" lg:px-[110px] w-full max-w-[1920px] mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
